/*
 * generated by Xtext 2.10.0
 */
package org.browser.automation


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class BroStandaloneSetup extends BroStandaloneSetupGenerated {

	def static void doSetup() {
		new BroStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
